import android.util.Log
import kotlinx.coroutines.*

/**
 * Handle for a single logical conversation with the agent.
 *
 * `done()` resolves with the agent's `AgentOutput` (status `final_response`)
 * or rejects with the `AgentError` content. `sendFeedback(value)`
 * answers the most recent `human_input_request` for this run by sending a
 * `user_reply` carrying the matching `reply_id`. Multi-turn HITL stays
 * inside one `Run` until the agent emits a terminal event.
 */
class Run(private val thread: AgentThread) {

    /**
     * The outbound `ref_id` generated by the SDK when the originating
     * `user_input` was pushed. Empty until the push promise resolves.
     */
    var refId: String = ""
        private set

    private val doneDeferred = CompletableDeferred<AgentOutput>()
    private var latestHumanInputRef: String? = null
    private var humanInputTimer: Job? = null
    private var closed = false

    private val scope = CoroutineScope(Dispatchers.Default + SupervisorJob())

    /** @internal — set by AgentThread once the push promise resolves. */
    fun setRefId(refId: String) {
        this.refId = refId
    }

    /** @internal — feed an inbound event to this run. */
    fun push(evt: AgentEventOrUnknown) {
        if (closed) return

        when (evt.event) {
            "human_input_request" -> {
                val content = when (val raw = evt.content) {
                    is HumanInputRequest -> raw
                    is Map<*, *> -> HumanInputRequest(
                        thread_id = raw["thread_id"]?.toString().orEmpty(),
                        ref_id = raw["ref_id"]?.toString().orEmpty(),
                        agent_id = raw["agent_id"]?.toString().orEmpty(),
                        reply_to = raw["reply_to"]?.toString().orEmpty(),
                        prompt = raw["prompt"]?.toString().orEmpty(),
                        context = (raw["context"] as? Map<*, *>)?.entries?.associate { (key, value) ->
                            key.toString() to value
                        },
                        expected_response_type = raw["expected_response_type"]?.toString()
                            ?: ExpectedResponseTypes.TEXT,
                        timeout = when (val timeoutRaw = raw["timeout"]) {
                            is Int -> timeoutRaw
                            is Number -> timeoutRaw.toInt()
                            else -> timeoutRaw?.toString()?.toIntOrNull()
                        },
                        schema = raw["schema"]
                    )
                    else -> return
                }
                // Prefer the inbound message's own ref_id; fall back to its
                // explicit reply_to when ref_id is missing.
                latestHumanInputRef =
                    content.ref_id.takeIf { it.isNotEmpty() }
                        ?: content.reply_to.takeIf { it.isNotEmpty() }

                // Client-side timeout enforcement. If the agent advertises
                // a `timeout` (seconds), reject `done()` with HUMAN_INPUT_TIMEOUT
                // when the user hasn't responded in time. Cleared on next event or
                // on sendFeedback.
                clearHumanInputTimer()
                val timeoutSec = content.timeout
                if (timeoutSec != null && timeoutSec > 0) {
                    humanInputTimer = scope.launch {
                        delay(timeoutSec * 1000L)
                        if (closed) return@launch
                        val err = AgentError(
                            type = "agent_error_response",
                            status = "error",
                            code = "HUMAN_INPUT_TIMEOUT",
                            message = "No response received within ${timeoutSec}s for human_input_request.",
                            details = mapOf("prompt" to content.prompt, "timeout" to timeoutSec),
                            thread_id = content.thread_id.ifEmpty { "" },
                            ref_id = "",
                            agent_id = content.agent_id.ifEmpty { "" },
                            reply_to = latestHumanInputRef ?: ""
                        )
                        closed = true
                        doneDeferred.completeExceptionally(AgentErrorException(err))
                        thread.closeRun(this@Run)
                    }
                }
                thread.fireRequestFeedback(content, this)
            }

            "agent_output" -> {
                clearHumanInputTimer()
                closed = true
                val content = when (val raw = evt.content) {
                    is AgentOutput -> raw
                    is Map<*, *> -> AgentOutput(
                        thread_id = raw["thread_id"]?.toString().orEmpty(),
                        ref_id = raw["ref_id"]?.toString().orEmpty(),
                        agent_id = raw["agent_id"]?.toString().orEmpty(),
                        reply_to = raw["reply_to"]?.toString().orEmpty(),
                        type = raw["type"]?.toString() ?: "agent_general_response",
                        status = raw["status"]?.toString() ?: "final_response",
                        message = raw["message"]?.toString().orEmpty(),
                        data = (raw["data"] as? Map<*, *>)?.entries?.associate { (key, value) ->
                            key.toString() to value

                        },
                        metadata = (raw["metadata"] as? Map<*, *>)?.entries?.associate { (key, value) ->
                            key.toString() to value
                        }
                    )
                    else -> return
                }
                doneDeferred.complete(content)
                thread.closeRun(this)
            }

            "agent_error" -> {
                clearHumanInputTimer()
                closed = true
                val content = when (val raw = evt.content) {
                    is AgentError -> raw
                    is Map<*, *> -> AgentError(
                        thread_id = raw["thread_id"]?.toString().orEmpty(),
                        ref_id = raw["ref_id"]?.toString().orEmpty(),
                        agent_id = raw["agent_id"]?.toString().orEmpty(),
                        reply_to = raw["reply_to"]?.toString().orEmpty(),
                        type = raw["type"]?.toString() ?: "agent_error_response",
                        status = raw["status"]?.toString() ?: "error",
                        code = raw["code"]?.toString().orEmpty(),
                        message = raw["message"]?.toString().orEmpty(),
                        details = (raw["details"] as? Map<*, *>)?.entries?.associate { (key, value) ->
                            key.toString() to value
                        }
                    )
                    else -> return
                }
                doneDeferred.completeExceptionally(AgentErrorException(content))
                thread.closeRun(this)
            }
            else -> {
                // agent_wait / planner_correction / unknown — do not terminate.
            }
        }
    }

    private fun clearHumanInputTimer() {
        humanInputTimer?.cancel()
        humanInputTimer = null
    }

    /**
     * Suspends until the agent's terminal `agent_output`, throws on `agent_error`
     * (wrapped in `AgentErrorException`) or transport-level errors.
     */
    suspend fun done(): AgentOutput {
        return doneDeferred.await()
    }

    /**
     * Send a reply to the most recent `human_input_request`. Throws if no
     * input is currently pending. The reply is sent as `user_reply` with
     * `reply_id` set to the originating request's `ref_id`.
     */
    suspend fun sendFeedback(value: Any?) {
        val replyId = latestHumanInputRef
            ?: throw IllegalStateException(
                "Run.sendFeedback: no pending human_input_request to respond to."
            )
        // Consume the pending input *before* sending so a reentrant handler
        // doesn't double-respond.
        latestHumanInputRef = null
        clearHumanInputTimer()
        thread.sendReply(value, replyId)
    }

    /** @internal — called by AgentThread when the run is force-closed. */
    fun close(reason: String = "Run closed before terminal event") {
        if (closed) return
        clearHumanInputTimer()
        closed = true
        doneDeferred.completeExceptionally(IllegalStateException(reason))
    }

    /** Whether the run has terminated. */
    fun isClosed(): Boolean = closed
}

/**
 * Wraps an `AgentError` as a throwable exception so it can be surfaced
 * through `CompletableDeferred.completeExceptionally`.
 */
class AgentErrorException(agentError: AgentError) :
    Exception("Agent error [${agentError.code}]: ${agentError.message}")
